### PR TITLE
Issue 305 client write

### LINKED ISSUE #305: Creating file on AWS SFTP managed services always get "Cannot open file in mode: WRITE|TRUNCATE|CREATE|READ" (SSH_FX_OP_UNSUPPORTED)
When using AWS SFTP managed services, sftp client always failed to create files. Create function (`client.Create()` ) always returned error with message "Cannot open file in mode: WRITE|TRUNCATE|CREATE|READ" (SSH_FX_OP_UNSUPPORTED).

This error only happened on AWS SFTP managed services. Regular SFTP server has no issue. The same endpoint were tested using sftp command, FileZilla and even .Net sftp library and all working normally. Only go sftp package were returned the error.

### PR DESCRIPTION
**Pull request by eikenb**
Fixes #305

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -167,6 +167,9 @@ type Client struct {
 // already exists. If successful, methods on the returned File can be used for
 // I/O; the associated file descriptor has mode O_RDWR. If you need more
 // control over the flags/mode used to open the file see client.OpenFile.
+// Note that some SFTP servers (eg. AWS Transfer) do not support opening files
```
Comment (puellanivis) [inline client.go]: I’d probably recommend a paragraph break here.

Comment (eikenb) [reply client.go]: Thanks.

**Comment by eikenb** [comment]
Issue 305 client write

Fixes #305
